version: 2.0
jobs:
  build:
    docker:
      - image: mrpt/mrpt-build-env:full
    working_directory: ~/workspace/mrpt
    environment:
      - TASK: build
      - BUILD_TYPE: Debug
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: travis/travis_main.sh
      - run: mkdir ../archive
      - run: tar -jcvf ../archive/snapshot.tbz2 .
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - archive
  test:
    docker:
      - image: mrpt/mrpt-build-env:full
    working_directory: ~/workspace/mrpt
    environment:
      - TASK: test
      - BUILD_TYPE: Debug
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: tar -jxvf ../archive/snapshot.tbz2
      - run: travis/travis_main.sh


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
